### ISSUE TITLE
PrimeNG 16 support

### ISSUE THREAD

**Issue by yrandin** [primefaces/primeng-sass-theme#10]
Hello,
What is the plan regarding the version 16 ?
Is there anything that needs to be updated so it can be used with PrimeNG 16 ?
Best Regards,
Yann

**Comment by avine** [comment]
I have tried to use the current latest version primeng-sass-theme@15.4.1 with primeng@16.
But for example, the `<pi-menubar>` was not rendered properly.
So, indeed, we certainly need to wait for primeng-sass-theme@16

**Comment by avine** [comment]
Here it is : https://github.com/primefaces/primeng-sass-theme/releases/tag/16.0.2 👍

**Comment by AgnesGehle** [comment]
This was really helpful, I had the same problem and found this conversation. Thanks!

**Comment by cetincakiroglu** [comment]
Hi,

Closing the issue since it's a discussion and answer is provided by @avine
