### ISSUE TITLE
Stepper CSS different from primeng project (v17.13.0)

### ISSUE THREAD

**Issue by meriturva** [primefaces/primeng-sass-theme#121]
Just see:

https://github.com/primefaces/primeng/blob/a3b991d5f925706ef1e786b626ca01701beb91af/src/assets/components/themes/mira/theme.css#L4036

is completely different compared to the one on this repo:

https://github.com/primefaces/primeng-sass-theme/blob/afaed38cc7875c7f32dec11923c77af31da76e1c/theme-base/components/panel/_stepper.scss#L12

**So basically Stepper doesn't work correctly even with version 17.13.0.**

I'm really confused but I guess that, to make this repo the 'only' one about theming aspects you have to use it on primeng components repo. Am I right?

why this repo is not used on [primefaces/primeng/package.json](https://github.com/primefaces/primeng/blob/a3b991d5f925706ef1e786b626ca01701beb91af/package.json) ?

Thanks!

**Comment by gregorwinkler** [comment]
I have the same issue and temporarily copied over lines 4036-4044 from https://github.com/primefaces/primeng/blob/a3b991d5f925706ef1e786b626ca01701beb91af/src/assets/components/themes/mira/theme.css into an own extension file on top of the base theme. By that it works, but should still be fixed properly in this repository.

**Comment by cetincakiroglu** [comment]
Thanks a lot for reporting the issue, _stepper.scss import is missing in _component.scss. Fixing it now.
