### ISSUE TITLE
Theme Desginer / Code Editor 

### ISSUE THREAD

**Issue by The-Real-1** [primefaces/primeng-sass-theme#43]
Hi,

I have a question about the roadmap of the Theme designer / Code Editor.
I have seen this note about the incomming architecture : 

```
Note: In upcoming versions, theming architecture will be redesigned to utilize CSS variables instead of SCSS variables in a backward compatible way for a dynamic approach. In addition, a new Unstyled mode will be provided as an alternative to the default styling so that CSS libraries like Tailwind or Bootstrap can be used to style the components. This work is planned to be completed in Q3 2023.
```

Will this be a breaking change or a compatibility layer will be available ?

Another question : 

Is it planned to migrate from Sass @import to @use in further releases ?

Thanks a lot,

Regards

**Comment by SoyDiego** [comment]
> Hi,
> 
> I have a question about the roadmap of the Theme designer / Code Editor. I have seen this note about the incomming architecture :
> 
> ```
> Note: In upcoming versions, theming architecture will be redesigned to utilize CSS variables instead of SCSS variables in a backward compatible way for a dynamic approach. In addition, a new Unstyled mode will be provided as an alternative to the default styling so that CSS libraries like Tailwind or Bootstrap can be used to style the components. This work is planned to be completed in Q3 2023.
> ```
> 
> Will this be a breaking change or a compatibility layer will be available ?
> 
> Another question :
> 
> Is it planned to migrate from Sass @import to @use in further releases ?
> 
> Thanks a lot,
> 
> Regards

Hi, I recomend ask here: https://github.com/orgs/primefaces/discussions

**Comment by The-Real-1** [comment]
Thanks , and sorry for the mistake.
