### ISSUE TITLE
New @layer implementation

### ISSUE THREAD

**Issue by tugcekucukoglu** [primefaces/primeng-sass-theme#47]

**Comment by nhoizey** [comment]
@tugcekucukoglu does it mean that all CSS code is now inside `@layer`?

It would mean that 10% of people, using older devices/browsers, won't have these styles anymore: https://caniuse.com/?search=%40layer

Or will you provide both versions, with and without `@layer`?

**Comment by atamansv** [comment]
Related issue: https://github.com/primefaces/primeng/issues/14381
It's 6% now, but it's still a lot.
