### ISSUE TITLE
Dropdown | missing invalid styles

### ISSUE THREAD

**Issue by wawyed** [primefaces/primeng-sass-theme#77]
There doesn't seem to be any invalid border for Dropdown component in the theme-base. The only thing I can see it p-invalid which I'm not sure how you apply to it? I'd expect to rely on .ng-invalid.ng-dirty as other form fields.

https://github.com/primefaces/primeng-sass-theme/blob/f0ef59b267a7d4e015e0a0b8c81b46fae4e16d57/theme-base/components/input/_dropdown.scss#L49

**Comment by cetincakiroglu** [comment]
fixed in https://github.com/primefaces/primeng-sass-theme/commit/5b79839aca6d4041441c473e70c55ab2d5675fb9

Thanks for reporting the issue!
